import java.util.Hashtable;
//SRM 599 Div 1 250
//Passed System Tests
public class BigFatInteger
{
	public int minOperations(int A, int B)
	{
		Hashtable<Integer,Integer> factors = new Hashtable<Integer,Integer>();
		int cur = A;
		for(int div=2;div<=A;++div) {
			if(div>cur) {
				break;
			} 
			if(cur%div==0) {
				int cnt = 0;
				while(cur%div==0) {
					cur/=div;
					++cnt;
				}
				factors.put(div, cnt);
			}
		}
		int max = -1;
		for(int v : factors.values()) {
			int m = v * B;
			max = Math.max(max, m);
		}
		int numMoves = 1, pos = 1;
		while(pos<max) {
			pos*=2;
			++numMoves;			
		}
		int ret = numMoves + factors.size() - 1;
		return ret;
	}
	
	// BEGIN KAWIGIEDIT TESTING
	// Generated by KawigiEdit 2.1.4 (beta) modified by pivanof
	private static boolean KawigiEdit_RunTest(int testNum, int p0, int p1, boolean hasAnswer, int p2) {
		System.out.print("Test " + testNum + ": [" + p0 + "," + p1);
		System.out.println("]");
		BigFatInteger obj;
		int answer;
		obj = new BigFatInteger();
		long startTime = System.currentTimeMillis();
		answer = obj.minOperations(p0, p1);
		long endTime = System.currentTimeMillis();
		boolean res;
		res = true;
		System.out.println("Time: " + (endTime - startTime) / 1000.0 + " seconds");
		if (hasAnswer) {
			System.out.println("Desired answer:");
			System.out.println("\t" + p2);
		}
		System.out.println("Your answer:");
		System.out.println("\t" + answer);
		if (hasAnswer) {
			res = answer == p2;
		}
		if (!res) {
			System.out.println("DOESN'T MATCH!!!!");
		} else if ((endTime - startTime) / 1000.0 >= 2) {
			System.out.println("FAIL the timeout");
			res = false;
		} else if (hasAnswer) {
			System.out.println("Match :-)");
		} else {
			System.out.println("OK, but is it right?");
		}
		System.out.println("");
		return res;
	}
	public static void main(String[] args) {
		boolean all_right;
		all_right = true;
		
		int p0;
		int p1;
		int p2;
		
		// ----- test 0 -----
		p0 = 6;
		p1 = 1;
		p2 = 2;
		all_right = KawigiEdit_RunTest(0, p0, p1, true, p2) && all_right;
		// ------------------
		
		// ----- test 1 -----
		p0 = 162;
		p1 = 1;
		p2 = 4;
		all_right = KawigiEdit_RunTest(1, p0, p1, true, p2) && all_right;
		// ------------------
		
		// ----- test 2 -----
		p0 = 999983;
		p1 = 9;
		p2 = 5;
		all_right = KawigiEdit_RunTest(2, p0, p1, true, p2) && all_right;
		// ------------------
		
		// ----- test 3 -----
		p0 = 360;
		p1 = 8;
		p2 = 8;
		all_right = KawigiEdit_RunTest(3, p0, p1, true, p2) && all_right;
		// ------------------
		
		if (all_right) {
			System.out.println("You're a stud (at least on the example cases)!");
		} else {
			System.out.println("Some of the test cases had errors.");
		}
	}
	// END KAWIGIEDIT TESTING
}
//Powered by KawigiEdit 2.1.4 (beta) modified by pivanof!
