//601 Div 1 250
//Passed System Tests
public class WinterAndPresents
{
	public long getNumber(int[] apple, int[] orange)
	{
		int MAX = 2000000;
		
		int N = apple.length;	
		long ret = 0L;
		boolean notPossible = false;
		for(int X = 1; X<=MAX; ++X) {
			long minApple = 0, maxApple = 0;
			for(int i=0;i<N;++i) {
				if(apple[i]+orange[i]<X)
				{
					notPossible = true;
					break;
				}
				if(orange[i]>=X) 
					minApple += 0;
				else {
					minApple += X-orange[i];
				}
				if(apple[i]>=X)
					maxApple += X;
				else
					maxApple += (apple[i]);
			}
			
			if(notPossible)
				break; // higher X not possible
			
			long ways = maxApple - minApple + 1;
			ret += ways;
		}
		
		return ret;
	}
	
	// BEGIN KAWIGIEDIT TESTING
	// Generated by KawigiEdit 2.1.4 (beta) modified by pivanof
	private static boolean KawigiEdit_RunTest(int testNum, int[] p0, int[] p1, boolean hasAnswer, long p2) {
		System.out.print("Test " + testNum + ": [" + "{");
		for (int i = 0; p0.length > i; ++i) {
			if (i > 0) {
				System.out.print(",");
			}
			System.out.print(p0[i]);
		}
		System.out.print("}" + "," + "{");
		for (int i = 0; p1.length > i; ++i) {
			if (i > 0) {
				System.out.print(",");
			}
			System.out.print(p1[i]);
		}
		System.out.print("}");
		System.out.println("]");
		WinterAndPresents obj;
		long answer;
		obj = new WinterAndPresents();
		long startTime = System.currentTimeMillis();
		answer = obj.getNumber(p0, p1);
		long endTime = System.currentTimeMillis();
		boolean res;
		res = true;
		System.out.println("Time: " + (endTime - startTime) / 1000.0 + " seconds");
		if (hasAnswer) {
			System.out.println("Desired answer:");
			System.out.println("\t" + p2);
		}
		System.out.println("Your answer:");
		System.out.println("\t" + answer);
		if (hasAnswer) {
			res = answer == p2;
		}
		if (!res) {
			System.out.println("DOESN'T MATCH!!!!");
		} else if ((endTime - startTime) / 1000.0 >= 2) {
			System.out.println("FAIL the timeout");
			res = false;
		} else if (hasAnswer) {
			System.out.println("Match :-)");
		} else {
			System.out.println("OK, but is it right?");
		}
		System.out.println("");
		return res;
	}
	public static void main(String[] args) {
		boolean all_right;
		all_right = true;
		
		int[] p0;
		int[] p1;
		long p2;
		
		// ----- test 0 -----
		p0 = new int[]{1};
		p1 = new int[]{1};
		p2 = 3L;
		all_right = KawigiEdit_RunTest(0, p0, p1, true, p2) && all_right;
		// ------------------
		
		// ----- test 1 -----
		p0 = new int[]{1,2,0,3};
		p1 = new int[]{4,5,0,6};
		p2 = 0L;
		all_right = KawigiEdit_RunTest(1, p0, p1, true, p2) && all_right;
		// ------------------
		
		// ----- test 2 -----
		p0 = new int[]{2,2,2};
		p1 = new int[]{2,2,2};
		p2 = 16L;
		all_right = KawigiEdit_RunTest(2, p0, p1, true, p2) && all_right;
		// ------------------
		
		// ----- test 3 -----
		p0 = new int[]{7,4,5};
		p1 = new int[]{1,10,2};
		p2 = 46L;
		all_right = KawigiEdit_RunTest(3, p0, p1, true, p2) && all_right;
		// ------------------
		
		// ----- test 4 -----
		p0 = new int[]{1000000};
		p1 = new int[]{1000000};
		p2 = 1000002000000L;
		all_right = KawigiEdit_RunTest(4, p0, p1, true, p2) && all_right;
		// ------------------
		
		p0 = new int[]{1000000,1000000, 1000000,1000000, 1000000,1000000, 1000000,1000000, 1000000,1000000, 1000000,1000000, 1000000,1000000, 1000000,1000000, 1000000,1000000, 1000000,1000000, 1000000,1000000, 1000000,1000000, 1000000,1000000, 1000000,1000000,1000000,1000000, 1000000,1000000, 1000000,1000000, 1000000,1000000, 1000000,1000000, 1000000,1000000, 1000000,1000000, 1000000,1000000, 1000000,1000000, 1000000,1000000, 1000000,1000000};
		p1 = new int[]{1000000,1000000, 1000000,1000000, 1000000,1000000, 1000000,1000000, 1000000,1000000, 1000000,1000000, 1000000,1000000, 1000000,1000000, 1000000,1000000, 1000000,1000000, 1000000,1000000, 1000000,1000000, 1000000,1000000, 1000000,1000000, 1000000,1000000, 1000000,1000000, 1000000,1000000, 1000000,1000000, 1000000,1000000, 1000000,1000000, 1000000,1000000, 1000000,1000000, 1000000,1000000, 1000000,1000000, 1000000,1000000};
		p2 = 50000002000000L;
		all_right = KawigiEdit_RunTest(5, p0, p1, true, p2) && all_right;
		
		if (all_right) {
			System.out.println("You're a stud (at least on the example cases)!");
		} else {
			System.out.println("Some of the test cases had errors.");
		}
	}
	// END KAWIGIEDIT TESTING
}
//Powered by KawigiEdit 2.1.4 (beta) modified by pivanof!
